---
- name: "{{ install_name }} installation and configuration"
  hosts: "{{ hosts_group_name | default('all') }}"
  remote_user: root
  vars:
    wildfly_install_workdir: '/opt'
    install_name: "{{ override_install_name | default('wildfly') }}"
    wildfly_user: "{{ install_name }}"
    wildfly_config_base: standalone-ha.xml
    wildfly_home: "{{ wildfly_install_workdir }}/{{ install_name }}-{{ wildfly_version }}"
    app:
      name: 'test-app.war'
      url: 'https://raw.githubusercontent.com/ansible-middleware/wildfly/main/molecule/files/test-app.war'
    ansible_distribution: 'RedHat'
  collections:
    - middleware_automation.wildfly
  roles:
    - middleware_automation.wildfly.wildfly_install
  tasks:
    - name: "Download application {{ app.name }}"
      ansible.builtin.get_url:
        url: "{{ app.url }}"
        dest: "{{ wildfly_home }}/standalone/deployments/{{ app.name }}"
        owner: "{{ wildfly_user }}"
        group: "{{ wildfly_user }}"
        mode: '0644'

    - name: "Set permissions on WildFly home"
      ansible.builtin.file:
        path: "{{ wildfly_home }}"
        owner: "{{ wildfly_user }}"
        group: "{{ wildfly_user }}"
        recurse: true
